; PCB GCode generated by RepRap Java Host Software
; Created: 2022-04-22:02-12-26
; Gerber tracks and pads file: minikame-Edge.Cuts.gbr
; Drill file: minikame.drl
;#!RECTANGLE: <BOX x:[l:10.0, h:58.91799999999998], y:[l:9.999999999999986, h:50.282]>
;#!LAYER: 1/1
G21 ;metric
G90 ;absolute positioning
M140 S0.0 ;set bed temperature and return
T0; select new extruder
G28; go home
G92 E0 ;zero the extruded length
G1 F50.0; Z feedrate
G1 Z0.0; Z clearance height
G1 F0.0; XY feedrate
M0 ; stop RepRap
